"""Runtime archives contain only deployable files and work outside the checkout."""

import os
from pathlib import Path, PurePosixPath
import subprocess
import sys
import textwrap
import zipfile

import pytest

from scripts import build_distribution as distribution


ARCHIVE_ROOT = "kovaaks-tracker"
REQUIRED_FILES = {
    "kovaaks_web.py": "from kovaaks.app import main\n",
    "kovaaks/__init__.py": "",
    "kovaaks/app.py": "def main():\n    pass\n",
    "kovaaks/web/index.html": '<script src="script.js"></script>\n',
    "kovaaks/web/script.js": 'console.log("tracker");\n',
    "kovaaks/web/style.css": "body { color: white; }\n",
    "requirements/runtime.txt": "requests>=2.28.0\n",
    "docs/INSTALL.md": "Install the runtime requirements and run kovaaks_web.py.\n",
    "LICENSE": "Example license text.\n",
}


@pytest.fixture
def source_tree(tmp_path):
    """Create an isolated checkout with private and developer-only decoy files."""
    source = tmp_path / "source"
    files = {
        **REQUIRED_FILES,
        "kovaaks/runtime.py": 'MESSAGE = "runtime module"\n',
        "tests/test_private.py": "private test fixture",
        "scripts/dev_tool.py": "developer tool",
        "scratch/sample.json": "scratch data",
        "README.md": "full source documentation",
        "AGENTS.md": "development instructions",
        "pytest.ini": "[pytest]\n",
        "requirements/dev.txt": "pytest\n",
        "docs/assets/screenshot.png": "unneeded image",
        ".git/config": "repository metadata",
        ".github/workflows/tests.yml": "CI configuration",
        ".venv/private.txt": "virtual environment",
        "config.json": "private legacy config",
        "kovaaks.log": "private legacy log",
        "data/config.json": "private current config",
        "data/kovaaks.log": "private current log",
        "data/scores_cache.json.gz": "private score cache",
        "data/scenarios.json.gz": "downloaded dataset",
        "kovaaks/__pycache__/app.cpython-314.pyc": "generated bytecode",
        "kovaaks/private.json": "private adjacent data",
        "kovaaks/nested/test_internal.py": "non-runtime nested Python",
        "kovaaks/web/private.json": "private adjacent UI data",
    }
    for relative, content in files.items():
        path = source / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return source


def test_runtime_archive_contains_only_allowlisted_payload(source_tree):
    output = source_tree / "dist" / "runtime.zip"

    assert distribution.build_distribution(output, source_dir=source_tree) == output

    expected = {
        **REQUIRED_FILES,
        "kovaaks/runtime.py": 'MESSAGE = "runtime module"\n',
    }
    expected["docs/README.md"] = expected.pop("docs/INSTALL.md")
    expected["docs/LICENSE"] = expected.pop("LICENSE")
    with zipfile.ZipFile(output) as archive:
        payload = {
            name: archive.read(name).decode("utf-8")
            for name in archive.namelist()
            if not name.endswith("/")
        }
        assert payload == {
            f"{ARCHIVE_ROOT}/{relative}": content
            for relative, content in expected.items()
        }
        root_files = {
            path.name for name in payload
            if len((path := PurePosixPath(name)).parts) == 2
        }
        assert root_files == {"kovaaks_web.py"}
        assert archive.testzip() is None


def test_runtime_archive_is_reproducible_despite_file_metadata(source_tree, tmp_path):
    first = distribution.build_distribution(tmp_path / "first.zip", source_dir=source_tree)
    for path in source_tree.rglob("*"):
        if path.is_file():
            os.utime(path, (1_000_000_000, 1_000_000_000))
            path.chmod(0o600)

    second = distribution.build_distribution(tmp_path / "second.zip", source_dir=source_tree)

    assert first.read_bytes() == second.read_bytes()


@pytest.mark.parametrize("missing", REQUIRED_FILES)
def test_missing_required_file_rejects_incomplete_archive(source_tree, tmp_path, missing):
    (source_tree / missing).unlink()
    output = tmp_path / "runtime.zip"

    with pytest.raises((OSError, ValueError)):
        distribution.build_distribution(output, source_dir=source_tree)

    assert not output.exists()


@pytest.mark.parametrize(
    "relative",
    ["kovaaks_web.py", "kovaaks/runtime.py", "kovaaks/web/index.html", "LICENSE"],
)
def test_included_symlink_is_rejected(source_tree, tmp_path, relative):
    path = source_tree / relative
    outside = tmp_path / "private-target"
    path.rename(outside)
    try:
        path.symlink_to(outside)
    except (NotImplementedError, OSError) as exc:
        pytest.skip(f"Creating symlinks is not supported: {exc}")
    output = tmp_path / "runtime.zip"

    with pytest.raises((OSError, ValueError)):
        distribution.build_distribution(output, source_dir=source_tree)

    assert not output.exists()


@pytest.mark.parametrize("relative", ["kovaaks", "kovaaks/web", "requirements", "docs"])
def test_symlink_ancestor_is_rejected(source_tree, tmp_path, relative):
    path = source_tree / relative
    outside = tmp_path / "private-directory"
    path.rename(outside)
    try:
        path.symlink_to(outside, target_is_directory=True)
    except (NotImplementedError, OSError) as exc:
        pytest.skip(f"Creating symlinks is not supported: {exc}")
    output = tmp_path / "runtime.zip"

    with pytest.raises((OSError, ValueError)):
        distribution.build_distribution(output, source_dir=source_tree)

    assert not output.exists()


def test_incomplete_source_preserves_previous_archive(source_tree, tmp_path):
    output = tmp_path / "runtime.zip"
    distribution.build_distribution(output, source_dir=source_tree)
    previous = output.read_bytes()
    (source_tree / "kovaaks/web/script.js").unlink()

    with pytest.raises((OSError, ValueError)):
        distribution.build_distribution(output, source_dir=source_tree)

    assert output.read_bytes() == previous


def test_mid_build_failure_preserves_previous_archive_and_cleans_temp(
    source_tree, tmp_path, monkeypatch,
):
    output = tmp_path / "dist" / "runtime.zip"
    distribution.build_distribution(output, source_dir=source_tree)
    previous = output.read_bytes()
    attempted_writes = 0

    def fail_after_first(original):
        def write(*args, **kwargs):
            nonlocal attempted_writes
            attempted_writes += 1
            if attempted_writes > 1:
                raise OSError("simulated disk write failure")
            return original(*args, **kwargs)
        return write

    monkeypatch.setattr(zipfile.ZipFile, "write", fail_after_first(zipfile.ZipFile.write))
    monkeypatch.setattr(zipfile.ZipFile, "writestr", fail_after_first(zipfile.ZipFile.writestr))

    with pytest.raises(OSError, match="simulated disk write failure"):
        distribution.build_distribution(output, source_dir=source_tree)

    assert attempted_writes > 1
    assert output.read_bytes() == previous
    assert list(output.parent.iterdir()) == [output]


def test_extracted_runtime_starts_from_unrelated_working_directory(tmp_path):
    """Exercise the shipped launcher and resources without GUI or account access."""
    output = distribution.build_distribution(tmp_path / "runtime.zip")
    extracted = tmp_path / "extracted"
    with zipfile.ZipFile(output) as archive:
        archive.extractall(extracted)
    application = extracted / ARCHIVE_ROOT
    unrelated = tmp_path / "unrelated"
    unrelated.mkdir()
    script = textwrap.dedent("""\
        import pathlib
        import runpy
        import sys
        from types import SimpleNamespace

        application = pathlib.Path(sys.argv[1]).resolve()
        sys.path.insert(0, str(application))
        initial_directory = pathlib.Path.cwd()

        def unexpected_access(*args, **kwargs):
            raise AssertionError("Runtime smoke attempted network or credential access")

        import requests
        requests.sessions.Session.request = unexpected_access
        import kovaaks.credentials as credentials
        credentials.get_password = unexpected_access
        credentials.set_password = unexpected_access
        credentials.delete_password = unexpected_access
        import kovaaks.logging_helpers as logging_helpers
        logging_helpers.LOG_FILE = str(initial_directory / "smoke.log")

        events = []
        window = object()

        class FakeAPI:
            def set_window(self, value):
                assert value is window
                events.append("set_window")

            def shutdown(self):
                events.append("shutdown")

        def create_window(title, url, **kwargs):
            assert isinstance(kwargs["js_api"], FakeAPI)
            path = pathlib.Path(url)
            assert path.is_absolute()
            assert path == application / "kovaaks" / "web" / "index.html"
            assert path.is_file()
            assert (path.parent / "script.js").is_file()
            assert (path.parent / "style.css").is_file()
            events.append("create_window")
            return window

        sys.modules["webview"] = SimpleNamespace(
            create_window=create_window,
            start=lambda **kwargs: events.append("start"),
        )
        from kovaaks import app
        assert pathlib.Path(app.__file__).resolve() == application / "kovaaks" / "app.py"
        app.KovaaksAPI = FakeAPI
        runpy.run_path(str(application / "kovaaks_web.py"), run_name="__main__")
        assert events == ["create_window", "set_window", "start", "shutdown"]
        assert pathlib.Path.cwd() == initial_directory
        print("extracted runtime started")
    """)

    result = subprocess.run(
        [sys.executable, "-c", script, str(application)],
        cwd=unrelated, capture_output=True, text=True, timeout=15,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "extracted runtime started" in result.stdout
